/* ------------------------------------
                std/io
    ---------------------------------
      SPDX-License-Identifier: MIT
      Copyrights (c) 2026 iamtowvee
  ------------------------------------- */

void *__sk__std_io_send(string line) {
    includeC ~~~
        if (line.__is_null) {
            printf("null");
        } else {
            printf("%s", line.value);
        }
    ~~~
}

string *__sk__std_io_input(string prompt = "") {
    includeC ~~~
        if (!prompt.__is_null) {
            printf("%s", prompt.value);
        }
        char buffer[256];
        fgets(buffer, sizeof(buffer), stdin);
        size_t len = strlen(buffer);
        if (len > 0 && buffer[len-1] == '\n') {
            buffer[len-1] = '\0';
        }
        return sk_string_new(buffer);
    ~~~
}

void sendln(any msg) {
    __sk__std_io_send($msg + "\n")
}

void sendf(any msg) {
    __sk__std_io_send($msg)
}

string input(string prefix = "") {
    return __sk__std_io_input(prefix)
}