/* ------------------------------------
                std/io
    ---------------------------------
      SPDX-License-Identifier: MIT
      Copyrights (c) 2026 iamtowvee
  ------------------------------------- */

void *__sk__std_io_send(string line) {
    includeC ```
        printf("%s", line);
    ```
}

string *__sk__std_io_input(string prompt = "") {
    includeC ```
        printf("%s", prompt);
        char buffer[256];
        fgets(buffer, sizeof(buffer), stdin);
        size_t len = strlen(buffer);
        if (len > 0 && buffer[len-1] == '\n') {
            buffer[len-1] = '\0';
        }
        return strdup(buffer);
    ```
}

void sendln(any msg) {
    __sk__std_io_send($msg + "\n")
}

void sendf(any msg) {
    __sk__std_io_send($msg)
}

void input(string prefix = "") {
    __sk__std_io_input(prefix)
}