/* ------------------------------------
                std/os
    ---------------------------------
      SPDX-License-Identifier: MIT
      Copyrights (c) 2026 iamtowvee
  ------------------------------------- */

string getEnv(string env) {
  includeC ~~~
    if (env.__is_null) return sk_string_new("");
    char* val = getenv(env.value);
    return sk_string_new(val ? val : "");
  ~~~
  return ""
}

void setEnv(string env, string val) {
  includeC ~~~
    if (env.__is_null || val.__is_null) return;
    #if defined(_WIN32)
        if (getenv(env.value) == NULL) {
            _putenv_s(env.value, val.value);
        }
    #elif defined(__linux__)
        setenv(env.value, val.value, 0);
    #endif
  ~~~
}

void setClearEnv(string env, string val, bool confirm) {
  if (!confirm) {
    return
  }
  includeC ~~~
    if (env.__is_null || val.__is_null) return;
    #if defined(_WIN32)
        _putenv_s(env.value, val.value);
    #elif defined(__linux__)
        setenv(env.value, val.value, 1);
    #endif
  ~~~
}

string getExePath() {
    includeC ~~~
        if (__sk__argc > 0 && __sk__argv[0]) {
            return sk_string_new(__sk__argv[0]);
        }
        return sk_string_new("");
    ~~~
    return ""
}

arr[string] getArgs() {
    includeC ~~~
        sk_array* arr = sk_array_new(sizeof(sk_string), 1);
        for (int i = 0; i < __sk__argc; i++) {
            sk_string s = sk_string_new(__sk__argv[i]);
            sk_array_push(arr, &s);
        }
        return sk_arr_new(arr);
    ~~~
    return []
}