/* ------------------------------------
                std/os
    ---------------------------------
      SPDX-License-Identifier: MIT
      Copyrights (c) 2026 iamtowvee
  ------------------------------------- */

string getEnv(string env) {
  includeC ~~~
    if (env.__is_null) return sk_string_new("");
    char* val = getenv(env.value);
    return sk_string_new(val ? val : "");
  ~~~
}

void setEnv(string env, string val) {
  includeC ~~~
    if (env.__is_null || val.__is_null) return;
    #if defined(_WIN32)
        if (getenv(env.value) == NULL) {
            _putenv_s(env.value, val.value);
        }
    #elif defined(__linux__)
        setenv(env.value, val.value, 0);
    #endif
  ~~~
}

void setClearEnv(string env, string val, bool confirm) {
  if (!confirm) {
    return
  }
  includeC ~~~
    if (env.__is_null || val.__is_null) return;
    #if defined(_WIN32)
        _putenv_s(env.value, val.value);
    #elif defined(__linux__)
        setenv(env.value, val.value, 1);
    #endif
  ~~~
}