/* ------------------------------------
                std/ref
    ---------------------------------
      SPDX-License-Identifier: MIT
      Copyrights (c) 2026 iamtowvee
  ------------------------------------- */

use #std/strings

/* === Errors === */

const VoidRefactorError{msg: string} = new Error

const VoidToIntRefactorError{msg: string} = new VoidRefactorError
const VoidToBoolRefactorError{msg: string} = new VoidRefactorError

/* === Basic === */

int toInt(any value) {
  int result = 0
  case (type(value)) {
    "int" {
      result = value
    },
    "float","double" {
      result = value.to_int()
    },
    "bool" {
      if (value) {
        result = 1
      } else {
        result = 0
      }
    },
    "void" {
      result = 0
    },
    "arr" {
      result = value.length
    },
    "string" {
      // TO-DO
      result = value.to_int()
    },
    _ {
      result = 0
    },
  }
  return result
}

bool toBool(any value) {
  case (type(value)) {
    "int","float","double" {
      if (value > 0) {
        return true
      } else {
        return false
      }
    },
    "bool" {
      return value
    },
    "void" {
      return false
    },
    "arr" {
      if (value.length > 0) {
        return true
      } else {
        return false
      }
    },
    "string" {
      if (value.length > 0) {
        if (value == "true") {
          return true
        } else {
          return false
        }
      } else {
        return false
      }
    },
    _ {
      return false
    },
  }
}

/* === Strict === */

int toIntStrict(any value) {
  int result = 0
  case (type(value)) {
    "int" {
      result = value
    },
    "float","double" {
      result = value.to_int()
    },
    "bool" {
      if (value) {
        result = 1
      } else {
        result = 0
      }
    },
    "void" {
      throw VoidToIntRefactorError{msg: "Cannot convert 'null' to int."}
    },
    "arr" {
      result = value.length
    },
    "string" {
      // TO-DO
      result = value.to_int()
    },
    _ {
      result = 0
    },
  }
  return result
}

bool toBoolStrict(any value) {
  case (type(value)) {
    "int","float","double" {
      if (value > 0) {
        return true
      } else {
        return false
      }
    },
    "bool" {
      return value
    },
    "void" {
      throw VoidToBoolRefactorError{msg: "Cannot convert 'null' to bool."}
    },
    "arr" {
      if (value.length > 0) {
        return true
      } else {
        return false
      }
    },
    "string" {
      if (value.length > 0) {
        if (value == "true") {
          return true
        } else {
          return false
        }
      } else {
        return false
      }
    },
    _ {
      return false
    },
  }
}