package backend

import (
	"fmt"
	"strings"
)

type CodeGenerator struct {
	IR       *IRProgram
	CSource  strings.Builder
	Includes []string
}

func NewCodeGenerator(ir *IRProgram) *CodeGenerator {
	cg := &CodeGenerator{
		IR:       ir,
		Includes: []string{"<stdio.h>", "<stdlib.h>", "<string.h>"},
	}
	return cg
}

func (cg *CodeGenerator) Generate() string {
	cg.CSource.Reset()

	cg.writeLine("// Generated by Skorpion Compiler")
	cg.writeLine("// Copyrights. (c) 2026 iamtowvee")
	cg.writeLine("")

	for _, inc := range cg.Includes {
		cg.writeLine(fmt.Sprintf("#include %s", inc))
	}

	cg.writeLine("")
	cg.writeLine("// Skorpion type definitions")
	cg.writeLine("typedef char* sk_string;")
	cg.writeLine("typedef int sk_bool;")
	cg.writeLine("#define true 1")
	cg.writeLine("#define false 0")
	cg.writeLine("")

	// ===== sk_any =====
	cg.writeLine("// Skorpion any type")
	cg.writeLine("typedef struct {")
	cg.writeLine("    int type;")
	cg.writeLine("    union {")
	cg.writeLine("        int i;")
	cg.writeLine("        float f;")
	cg.writeLine("        double d;")
	cg.writeLine("        sk_string s;")
	cg.writeLine("        sk_bool b;")
	cg.writeLine("        void* p;")
	cg.writeLine("    } data;")
	cg.writeLine("} sk_any;")
	cg.writeLine("")

	cg.writeLine("// Any constructors")
	cg.writeLine("sk_any any_int(int v) { sk_any a; a.type=0; a.data.i=v; return a; }")
	cg.writeLine("sk_any any_string(sk_string v) { sk_any a; a.type=1; a.data.s=v; return a; }")
	cg.writeLine("sk_any any_float(float v) { sk_any a; a.type=2; a.data.f=v; return a; }")
	cg.writeLine("sk_any any_double(double v) { sk_any a; a.type=3; a.data.d=v; return a; }")
	cg.writeLine("sk_any any_bool(sk_bool v) { sk_any a; a.type=4; a.data.b=v; return a; }")
	cg.writeLine("sk_any any_ptr(void* v) { sk_any a; a.type=5; a.data.p=v; return a; }")
	cg.writeLine("")

	cg.writeLine("// Any getters")
	cg.writeLine("int any_get_int(sk_any a) { return a.data.i; }")
	cg.writeLine("sk_string any_get_string(sk_any a) { return a.data.s; }")
	cg.writeLine("float any_get_float(sk_any a) { return a.data.f; }")
	cg.writeLine("double any_get_double(sk_any a) { return a.data.d; }")
	cg.writeLine("sk_bool any_get_bool(sk_any a) { return a.data.b; }")
	cg.writeLine("void* any_get_ptr(sk_any a) { return a.data.p; }")
	cg.writeLine("")

	cg.writeLine("// Any converters")
	cg.writeLine("int any_to_int(sk_any a) {")
	cg.writeLine("    switch (a.type) {")
	cg.writeLine("        case 0: return a.data.i;")
	cg.writeLine("        case 2: return (int)a.data.f;")
	cg.writeLine("        case 3: return (int)a.data.d;")
	cg.writeLine("        case 4: return a.data.b ? 1 : 0;")
	cg.writeLine("        case 1: return atoi(a.data.s);")
	cg.writeLine("        default: return 0;")
	cg.writeLine("    }")
	cg.writeLine("}")
	cg.writeLine("float any_to_float(sk_any a) {")
	cg.writeLine("    switch (a.type) {")
	cg.writeLine("        case 0: return (float)a.data.i;")
	cg.writeLine("        case 2: return a.data.f;")
	cg.writeLine("        case 3: return (float)a.data.d;")
	cg.writeLine("        case 4: return a.data.b ? 1.0f : 0.0f;")
	cg.writeLine("        case 1: return atof(a.data.s);")
	cg.writeLine("        default: return 0.0f;")
	cg.writeLine("    }")
	cg.writeLine("}")
	cg.writeLine("double any_to_double(sk_any a) {")
	cg.writeLine("    switch (a.type) {")
	cg.writeLine("        case 0: return (double)a.data.i;")
	cg.writeLine("        case 2: return (double)a.data.f;")
	cg.writeLine("        case 3: return a.data.d;")
	cg.writeLine("        case 4: return a.data.b ? 1.0 : 0.0;")
	cg.writeLine("        case 1: return atof(a.data.s);")
	cg.writeLine("        default: return 0.0;")
	cg.writeLine("    }")
	cg.writeLine("}")
	cg.writeLine("int any_to_bool(sk_any a) {")
	cg.writeLine("    switch (a.type) {")
	cg.writeLine("        case 0: return a.data.i != 0;")
	cg.writeLine("        case 2: return a.data.f != 0.0f;")
	cg.writeLine("        case 3: return a.data.d != 0.0;")
	cg.writeLine("        case 4: return a.data.b;")
	cg.writeLine("        case 1: return a.data.s[0] != '\\0';")
	cg.writeLine("        default: return 0;")
	cg.writeLine("    }")
	cg.writeLine("}")
	cg.writeLine("")

	// ===== sk_array =====
	cg.writeLine("// Skorpion array type")
	cg.writeLine("typedef struct {")
	cg.writeLine("    void* data;")
	cg.writeLine("    int length;")
	cg.writeLine("    int capacity;")
	cg.writeLine("    int elem_size;")
	cg.writeLine("    int elem_type; // 0=int,1=string,2=float,3=double,4=bool,5=any")
	cg.writeLine("} sk_array;")
	cg.writeLine("")
	cg.writeLine("sk_array* sk_array_new(int elem_size, int elem_type) {")
	cg.writeLine("    sk_array* a = malloc(sizeof(sk_array));")
	cg.writeLine("    a->data = NULL;")
	cg.writeLine("    a->length = 0;")
	cg.writeLine("    a->capacity = 0;")
	cg.writeLine("    a->elem_size = elem_size;")
	cg.writeLine("    a->elem_type = elem_type;")
	cg.writeLine("    return a;")
	cg.writeLine("}")
	cg.writeLine("")
	cg.writeLine("void sk_array_push(sk_array* a, void* elem) {")
	cg.writeLine("    if (a->length >= a->capacity) {")
	cg.writeLine("        a->capacity = a->capacity == 0 ? 4 : a->capacity * 2;")
	cg.writeLine("        a->data = realloc(a->data, a->capacity * a->elem_size);")
	cg.writeLine("    }")
	cg.writeLine("    memcpy((char*)a->data + a->length * a->elem_size, elem, a->elem_size);")
	cg.writeLine("    a->length++;")
	cg.writeLine("}")
	cg.writeLine("void sk_array_push_int(sk_array* a, int v) { sk_array_push(a, &v); }")
	cg.writeLine("void sk_array_push_string(sk_array* a, sk_string v) { sk_array_push(a, &v); }")
	cg.writeLine("void sk_array_push_float(sk_array* a, float v) { sk_array_push(a, &v); }")
	cg.writeLine("void sk_array_push_double(sk_array* a, double v) { sk_array_push(a, &v); }")
	cg.writeLine("void sk_array_push_bool(sk_array* a, sk_bool v) { sk_array_push(a, &v); }")
	cg.writeLine("void sk_array_push_any(sk_array* a, sk_any v) { sk_array_push(a, &v); }")
	cg.writeLine("void sk_array_push_arr(sk_array* a, sk_array* v) { sk_array_push(a, &v); }")
	cg.writeLine("")
	cg.writeLine("void* sk_array_get(sk_array* a, int index) {")
	cg.writeLine("    if (index < 0 || index >= a->length) return NULL;")
	cg.writeLine("    return (char*)a->data + index * a->elem_size;")
	cg.writeLine("}")
	cg.writeLine("")
	cg.writeLine("int sk_array_len(sk_array* a) { return a->length; }")
	cg.writeLine("")
	cg.writeLine("sk_array* sk_array_copy(sk_array* a) {")
	cg.writeLine("    sk_array* new = sk_array_new(a->elem_size, a->elem_type);")
	cg.writeLine("    for (int i = 0; i < a->length; i++) {")
	cg.writeLine("        sk_array_push(new, sk_array_get(a, i));")
	cg.writeLine("    }")
	cg.writeLine("    return new;")
	cg.writeLine("}")
	cg.writeLine("")
	cg.writeLine("void sk_array_free(sk_array* a) {")
	cg.writeLine("    free(a->data);")
	cg.writeLine("    free(a);")
	cg.writeLine("}")
	cg.writeLine("")

	cg.writeLine("sk_array* sk_range_new(int start, int end) {")
	cg.writeLine("    sk_array* a = sk_array_new(sizeof(int), 0);")
	cg.writeLine("    if (start <= end) {")
	cg.writeLine("        for (int i = start; i <= end; i++) {")
	cg.writeLine("            sk_array_push_int(a, i);")
	cg.writeLine("        }")
	cg.writeLine("    } else {")
	cg.writeLine("        for (int i = start; i >= end; i--) {")
	cg.writeLine("            sk_array_push_int(a, i);")
	cg.writeLine("        }")
	cg.writeLine("    }")
	cg.writeLine("    return a;")
	cg.writeLine("}")
	cg.writeLine("")

	cg.writeLine("// Forward declarations")
	cg.writeLine("sk_string sk_array_to_string(sk_array* a);")
	cg.writeLine("")

	// ===== any_to_string =====
	cg.writeLine("// Any to string")
	cg.writeLine("sk_string any_to_string(sk_any a) {")
	cg.writeLine("    char buf[64];")
	cg.writeLine("    switch (a.type) {")
	cg.writeLine("        case 0: snprintf(buf, 64, \"%d\", a.data.i); return strdup(buf);")
	cg.writeLine("        case 1: return strdup(a.data.s);")
	cg.writeLine("        case 2: snprintf(buf, 64, \"%f\", a.data.f); return strdup(buf);")
	cg.writeLine("        case 3: snprintf(buf, 64, \"%f\", a.data.d); return strdup(buf);")
	cg.writeLine("        case 4: return strdup(a.data.b ? \"true\" : \"false\");")
	cg.writeLine("        case 5: return sk_array_to_string((sk_array*)a.data.p);")
	cg.writeLine("        default: return strdup(\"unknown\");")
	cg.writeLine("    }")
	cg.writeLine("}")
	cg.writeLine("")

	// ===== sk_array_to_string (ПОСЛЕ any_to_string!) =====
	cg.writeLine("// Array to string")
	cg.writeLine("sk_string sk_array_to_string(sk_array* a) {")
	cg.writeLine("    char* buf = malloc(1024);")
	cg.writeLine("    strcpy(buf, \"[\");")
	cg.writeLine("    for (int i = 0; i < a->length; i++) {")
	cg.writeLine("        if (i > 0) strcat(buf, \", \");")
	cg.writeLine("        void* elem = sk_array_get(a, i);")
	cg.writeLine("        if (a->elem_type == 5) {")
	cg.writeLine("            sk_any* any = (sk_any*)elem;")
	cg.writeLine("            char* s = any_to_string(*any);")
	cg.writeLine("            strcat(buf, s);")
	cg.writeLine("        } else if (a->elem_type == 0) {")
	cg.writeLine("            char tmp[32]; snprintf(tmp, 32, \"%d\", *(int*)elem); strcat(buf, tmp);")
	cg.writeLine("        } else if (a->elem_type == 1) {")
	cg.writeLine("            strcat(buf, *(sk_string*)elem);")
	cg.writeLine("        } else if (a->elem_type == 2) {")
	cg.writeLine("            char tmp[32]; snprintf(tmp, 32, \"%f\", *(float*)elem); strcat(buf, tmp);")
	cg.writeLine("        } else if (a->elem_type == 3) {")
	cg.writeLine("            char tmp[32]; snprintf(tmp, 32, \"%f\", *(double*)elem); strcat(buf, tmp);")
	cg.writeLine("        } else if (a->elem_type == 4) {")
	cg.writeLine("            strcat(buf, *(sk_bool*)elem ? \"true\" : \"false\");")
	cg.writeLine("        } else if (a->elem_type == 6) {")
	cg.writeLine("			  sk_array* nested = *(sk_array**)elem;")
	cg.writeLine("			  char* s = sk_array_to_string(nested);")
	cg.writeLine("			  strcat(buf, s);")
	cg.writeLine("        }")
	cg.writeLine("    }")
	cg.writeLine("    strcat(buf, \"]\");")
	cg.writeLine("    return buf;")
	cg.writeLine("}")
	cg.writeLine("")

	// ===== Function prototypes =====
	cg.writeLine("// Function prototypes")
	for _, fn := range cg.IR.Functions {
		if fn.Name == "main" {
			continue
		}
		returnType := cg.typeToC(fn.ReturnType)
		params := []string{}
		for _, p := range fn.Params {
			params = append(params, fmt.Sprintf("%s %s", cg.typeToC(p.Type), p.Name))
		}
		paramsStr := strings.Join(params, ", ")
		if paramsStr == "" {
			paramsStr = "void"
		}
		cg.writeLine(fmt.Sprintf("%s %s(%s);", returnType, fn.Name, paramsStr))
	}
	cg.writeLine("")

	// ===== Inline C =====
	if cg.IR.InlineC != "" {
		cg.writeLine("// Inline C code")
		cg.writeLine(cg.IR.InlineC)
		cg.writeLine("")
	}

	// ===== Globals =====
	if len(cg.IR.Globals) > 0 {
		cg.writeLine("// Global variables")
		for _, g := range cg.IR.Globals {
			qualifier := ""
			if g.IsConst {
				qualifier = "const "
			}
			cg.writeLine(fmt.Sprintf("%s%s %s = %s;", qualifier, cg.typeToC(g.Type), g.Name, g.Value))
		}
		cg.writeLine("")
	}

	// ===== Functions =====
	for _, fn := range cg.IR.Functions {
		cg.generateFunction(&fn)
	}

	return cg.CSource.String()
}

func (cg *CodeGenerator) generateFunction(fn *IRFunction) {
	isMain := fn.Name == "main"

	var returnType string
	if isMain {
		returnType = "int"
	} else {
		returnType = cg.typeToC(fn.ReturnType)
	}

	var paramsStr string
	if isMain {
		paramsStr = "int argc, char** argv"
	} else {
		params := []string{}
		for _, p := range fn.Params {
			params = append(params, fmt.Sprintf("%s %s", cg.typeToC(p.Type), p.Name))
		}
		paramsStr = strings.Join(params, ", ")
		if paramsStr == "" {
			paramsStr = "void"
		}
	}

	cg.writeLine(fmt.Sprintf("%s %s(%s) {", returnType, fn.Name, paramsStr))

	if isMain {
		cg.writeLine("    (void)argc;")
		cg.writeLine("    (void)argv;")
	}

	if len(fn.Locals) > 0 {
		for _, local := range fn.Locals {
			cg.writeLine(fmt.Sprintf("    %s;", local))
		}
		cg.writeLine("")
	}

	for _, ins := range fn.Instructions {
		cg.generateInstruction(&ins, fn)
	}

	if fn.ReturnType == "void" && len(fn.Instructions) > 0 {
		lastIns := fn.Instructions[len(fn.Instructions)-1]
		if lastIns.Op != "ret" {
			if isMain {
				cg.writeLine("    return 0;")
			} else {
				cg.writeLine("    return;")
			}
		}
	}

	cg.writeLine("}")
	cg.writeLine("")
}

func (cg *CodeGenerator) generateInstruction(ins *IRInstruction, fn *IRFunction) {
	indent := "    "

	switch ins.Op {
	case "label":
		cg.writeLine(fmt.Sprintf("%s:", ins.Result))

	case "free":
		cg.writeLine(fmt.Sprintf("%sfree(%s);", indent, ins.Arg1))

	case "inline_c":
		lines := strings.Split(ins.Arg1, "\n")
		for _, line := range lines {
			if strings.TrimSpace(line) != "" {
				cg.writeLine(fmt.Sprintf("%s%s", indent, line))
			}
		}

	case "ternary":
		cg.writeLine(fmt.Sprintf("%s%s %s = %s ? %s : %s;",
			indent, ins.ReturnType, ins.Result, ins.Arg1, ins.Arg2, ins.Arg3))

	case "typeof_any":
		cg.writeLine(fmt.Sprintf("%ssk_string %s;", indent, ins.Result))
		cg.writeLine(fmt.Sprintf("%schar buf[32];", indent))
		cg.writeLine(fmt.Sprintf("%sswitch (%s.type) {", indent, ins.Arg1))
		cg.writeLine(fmt.Sprintf("%s    case 0: strcpy(buf, \"int\"); break;", indent))
		cg.writeLine(fmt.Sprintf("%s    case 1: strcpy(buf, \"string\"); break;", indent))
		cg.writeLine(fmt.Sprintf("%s    case 2: strcpy(buf, \"float\"); break;", indent))
		cg.writeLine(fmt.Sprintf("%s    case 3: strcpy(buf, \"double\"); break;", indent))
		cg.writeLine(fmt.Sprintf("%s    case 4: strcpy(buf, \"bool\"); break;", indent))
		cg.writeLine(fmt.Sprintf("%s    case 5: strcpy(buf, \"ptr\"); break;", indent))
		cg.writeLine(fmt.Sprintf("%s    case 6: strcpy(buf, \"ptr\"); break;", indent))
		cg.writeLine(fmt.Sprintf("%s    default: strcpy(buf, \"unknown\"); break;", indent))
		cg.writeLine(fmt.Sprintf("%s}", indent))
		cg.writeLine(fmt.Sprintf("%s%s = strdup(buf);", indent, ins.Result))

	case "comment":
		cg.writeLine(fmt.Sprintf("%s%s", indent, ins.Arg1))

	case "strcat":
		cg.writeLine(fmt.Sprintf("%schar %s[256];", indent, ins.Result))
		cg.writeLine(fmt.Sprintf("%sstrcpy(%s, %s);", indent, ins.Result, ins.Arg1))
		cg.writeLine(fmt.Sprintf("%sstrcat(%s, %s);", indent, ins.Result, ins.Arg2))

	case "to_string":
		// Проверяем, является ли аргумент any
		isAny := false
		for _, local := range fn.Locals {
			if strings.Contains(local, ins.Arg1) && strings.Contains(local, "sk_any") {
				isAny = true
				break
			}
		}
		if !isAny {
			for _, param := range fn.Params {
				if param.Name == ins.Arg1 && param.Type == "any" {
					isAny = true
					break
				}
			}
		}
		if isAny {
			cg.writeLine(fmt.Sprintf("%ssk_string %s = any_to_string(%s);", indent, ins.Result, ins.Arg1))
		} else {
			cg.writeLine(fmt.Sprintf("%schar %s[32];", indent, ins.Result))
			cg.writeLine(fmt.Sprintf("%ssnprintf(%s, 32, \"%%d\", %s);", indent, ins.Result, ins.Arg1))
		}

	case "$":
		// Проверяем, является ли аргумент any
		isAny := false
		for _, local := range fn.Locals {
			if strings.Contains(local, ins.Arg1) && strings.Contains(local, "sk_any") {
				isAny = true
				break
			}
		}
		if !isAny {
			for _, param := range fn.Params {
				if param.Name == ins.Arg1 && param.Type == "any" {
					isAny = true
					break
				}
			}
		}
		if isAny {
			cg.writeLine(fmt.Sprintf("%ssk_string %s = any_to_string(%s);", indent, ins.Result, ins.Arg1))
		} else {
			cg.writeLine(fmt.Sprintf("%schar %s[32];", indent, ins.Result))
			cg.writeLine(fmt.Sprintf("%ssnprintf(%s, 32, \"%%d\", %s);", indent, ins.Result, ins.Arg1))
		}

	case "ret":
		if ins.Arg1 != "" {
			cg.writeLine(fmt.Sprintf("%sreturn %s;", indent, ins.Arg1))
		} else if fn.Name == "main" {
			cg.writeLine(fmt.Sprintf("%sreturn 0;", indent))
		} else {
			cg.writeLine(fmt.Sprintf("%sreturn;", indent))
		}

	case "cast_bool_to_int":
		cg.writeLine(fmt.Sprintf("%sint %s = %s ? 1 : 0;", indent, ins.Result, ins.Arg1))
	case "cast_num_to_int":
		cg.writeLine(fmt.Sprintf("%sint %s = (int)%s;", indent, ins.Result, ins.Arg1))
	case "cast_str_to_int":
		cg.writeLine(fmt.Sprintf("%sint %s = atoi(%s);", indent, ins.Result, ins.Arg1))
	case "cast_bool_to_float":
		cg.writeLine(fmt.Sprintf("%sfloat %s = %s ? 1.0f : 0.0f;", indent, ins.Result, ins.Arg1))
	case "cast_num_to_float":
		cg.writeLine(fmt.Sprintf("%sfloat %s = (float)%s;", indent, ins.Result, ins.Arg1))
	case "cast_str_to_float":
		cg.writeLine(fmt.Sprintf("%sfloat %s = (float)atof(%s);", indent, ins.Result, ins.Arg1))
	case "cast_bool_to_double":
		cg.writeLine(fmt.Sprintf("%sdouble %s = %s ? 1.0 : 0.0;", indent, ins.Result, ins.Arg1))
	case "cast_num_to_double":
		cg.writeLine(fmt.Sprintf("%sdouble %s = (double)%s;", indent, ins.Result, ins.Arg1))
	case "cast_str_to_double":
		cg.writeLine(fmt.Sprintf("%sdouble %s = atof(%s);", indent, ins.Result, ins.Arg1))
	case "cast_bool_to_str":
		cg.writeLine(fmt.Sprintf("%ssk_string %s = strdup(%s ? \"true\" : \"false\");", indent, ins.Result, ins.Arg1))
	case "cast_num_to_str":
		cg.writeLine(fmt.Sprintf("%schar _buf_%s[64]; snprintf(_buf_%s, 64, \"%%g\", (double)%s); sk_string %s = strdup(_buf_%s);", indent, ins.Result, ins.Result, ins.Arg1, ins.Result, ins.Result))
	case "cast_num_to_bool":
		cg.writeLine(fmt.Sprintf("%sint %s = %s > 0;", indent, ins.Result, ins.Arg1))
	case "cast_str_to_bool":
		cg.writeLine(fmt.Sprintf("%sint %s = (%s[0] != '\\0');", indent, ins.Result, ins.Arg1))

	case "array_get":
		cg.writeLine(fmt.Sprintf("%svoid* %s = sk_array_get(%s, %s);", indent, ins.Result, ins.Arg1, ins.Arg2))
	case "array_len":
		cg.writeLine(fmt.Sprintf("%sint %s = sk_array_len(%s);", indent, ins.Result, ins.Arg1))
	case "array_get_any":
		cg.writeLine(fmt.Sprintf("%ssk_any %s = *(sk_any*)sk_array_get(%s, %s);", indent, ins.Result, ins.Arg1, ins.Arg2))
	case "array_get_typed":
		cg.writeLine(fmt.Sprintf("%s%s %s = *(%s*)sk_array_get(%s, %s);", indent, ins.ReturnType, ins.Result, ins.ReturnType, ins.Arg1, ins.Arg2))
	case "array_add":
		cg.writeLine(fmt.Sprintf("%ssk_array* %s = sk_array_copy(%s);", indent, ins.Result, ins.Arg1))
		cg.writeLine(fmt.Sprintf("%ssk_array_push(%s, &%s);", indent, ins.Result, ins.Arg2))

	case "call":
		if ins.Result != "" {
			returnType := ins.ReturnType
			if returnType == "" {
				returnType = "sk_string"
			}

			if returnType == "void" {
				cg.writeLine(fmt.Sprintf("%s%s(%s);", indent, ins.Arg1, ins.Arg2))
				if strings.HasPrefix(ins.Result, "t") {
					cg.writeLine(fmt.Sprintf("%sint %s = 0;", indent, ins.Result))
				}
			} else {
				if strings.HasPrefix(ins.Result, "t") {
					cg.writeLine(fmt.Sprintf("%s%s %s = %s(%s);", indent, returnType, ins.Result, ins.Arg1, ins.Arg2))
				} else {
					cg.writeLine(fmt.Sprintf("%s%s = %s(%s);", indent, ins.Result, ins.Arg1, ins.Arg2))
				}
			}
		} else {
			cg.writeLine(fmt.Sprintf("%s%s(%s);", indent, ins.Arg1, ins.Arg2))
		}

	case "if":
		cg.writeLine(fmt.Sprintf("%sif %s {", indent, ins.Result))
		cg.writeLine(fmt.Sprintf("%s    goto %s;", indent, ins.Arg1))
		cg.writeLine(fmt.Sprintf("%s} else {", indent))
		cg.writeLine(fmt.Sprintf("%s    goto %s;", indent, ins.Arg2))
		cg.writeLine(fmt.Sprintf("%s}", indent))

	case "goto":
		cg.writeLine(fmt.Sprintf("%sgoto %s;", indent, ins.Result))

	case "=":
		if ins.Arg1 == "NULL" {
			cg.writeLine(fmt.Sprintf("%s%s = NULL;", indent, ins.Result))
		} else {
			if isTempVar(ins.Result) {
				argType := "int"
				if strings.HasPrefix(ins.Arg1, "\"") && strings.HasSuffix(ins.Arg1, "\"") {
					argType = "sk_string"
				} else if strings.Contains(ins.Arg1, ".") {
					argType = "double"
				} else if ins.Arg1 == "true" || ins.Arg1 == "false" {
					argType = "sk_bool"
				}
				cg.writeLine(fmt.Sprintf("%s%s %s = %s;", indent, argType, ins.Result, ins.Arg1))
			} else {
				cg.writeLine(fmt.Sprintf("%s%s = %s;", indent, ins.Result, ins.Arg1))
			}
		}

	case "+", "-", "*", "/":
		if isTempVar(ins.Result) {
			cg.writeLine(fmt.Sprintf("%sint %s = %s %s %s;", indent, ins.Result, ins.Arg1, ins.Op, ins.Arg2))
		} else {
			cg.writeLine(fmt.Sprintf("%s%s = %s %s %s;", indent, ins.Result, ins.Arg1, ins.Op, ins.Arg2))
		}

	default:
		if ins.Result != "" && ins.Arg1 != "" && ins.Arg2 != "" {
			cg.writeLine(fmt.Sprintf("%s%s %s %s %s;", indent, ins.Result, ins.Op, ins.Arg1, ins.Arg2))
		} else if ins.Result != "" && ins.Arg1 != "" {
			cg.writeLine(fmt.Sprintf("%s%s %s %s;", indent, ins.Result, ins.Op, ins.Arg1))
		} else {
			cg.writeLine(fmt.Sprintf("%s%s;", indent, ins.Result))
		}
	}
}

func (cg *CodeGenerator) typeToC(typ string) string {
	switch typ {
	case "int":
		return "int"
	case "string":
		return "sk_string"
	case "float":
		return "float"
	case "double":
		return "double"
	case "bool":
		return "sk_bool"
	case "char":
		return "char"
	case "void":
		return "void"
	case "arr":
		return "void*"
	case "dict":
		return "void*"
	case "any":
		return "sk_any"
	default:
		return "int"
	}
}

func (cg *CodeGenerator) writeLine(line string) {
	cg.CSource.WriteString(line + "\n")
}

func isTempVar(name string) bool {
	if !strings.HasPrefix(name, "t") || len(name) < 2 {
		return false
	}
	// Всё после "t" должно быть цифрой
	for _, c := range name[1:] {
		if c < '0' || c > '9' {
			return false
		}
	}
	return true
}
