package backend

import (
	"fmt"
	"strings"
)

type CodeGenerator struct {
	IR       *IRProgram
	CSource  strings.Builder
	Includes []string
}

func NewCodeGenerator(ir *IRProgram) *CodeGenerator {
	cg := &CodeGenerator{
		IR:       ir,
		Includes: []string{"<stdio.h>", "<stdlib.h>", "<string.h>"},
	}
	return cg
}

func (cg *CodeGenerator) Generate() string {
	cg.CSource.Reset()

	// Заголовки
	cg.writeLine("// Generated by Skorpion Compiler")
	cg.writeLine("// Copyrights. (c) 2026 iamtowvee")
	cg.writeLine("")

	for _, inc := range cg.Includes {
		cg.writeLine(fmt.Sprintf("#include %s", inc))
	}

	// Типы
	cg.writeLine("")
	cg.writeLine("// Skorpion type definitions")
	cg.writeLine("typedef char* sk_string;")
	cg.writeLine("typedef int sk_bool;")
	cg.writeLine("#define true 1")
	cg.writeLine("#define false 0")
	cg.writeLine("")

	// УБИРАЕМ ГЛОБАЛЬНУЮ ВСТАВКУ INLINEC!
	// includeC теперь вставляется в функции через inline_c инструкции

	// Глобальные переменные
	if len(cg.IR.Globals) > 0 {
		cg.writeLine("// Global variables")
		for _, g := range cg.IR.Globals {
			qualifier := ""
			if g.IsConst {
				qualifier = "const "
			}
			cg.writeLine(fmt.Sprintf("%s%s %s = %s;", qualifier, cg.typeToC(g.Type), g.Name, g.Value))
		}
		cg.writeLine("")
	}

	// Функции
	for _, fn := range cg.IR.Functions {
		cg.generateFunction(&fn)
	}

	return cg.CSource.String()
}

func (cg *CodeGenerator) generateFunction(fn *IRFunction) {
	// Сигнатура
	returnType := cg.typeToC(fn.ReturnType)

	params := []string{}
	for _, p := range fn.Params {
		params = append(params, fmt.Sprintf("%s %s", cg.typeToC(p.Type), p.Name))
	}
	paramsStr := strings.Join(params, ", ")
	if paramsStr == "" {
		paramsStr = "void"
	}

	cg.writeLine(fmt.Sprintf("%s %s(%s) {", returnType, fn.Name, paramsStr))

	// Локальные переменные - используем typeToC, а не fixTypeInDeclaration
	if len(fn.Locals) > 0 {
		for _, local := range fn.Locals {
			// local уже содержит тип и имя: "int x"
			// Но тип может быть из IR, нужно преобразовать
			cg.writeLine(fmt.Sprintf("    %s;", local))
		}
		cg.writeLine("")
	}

	// Инструкции
	for _, ins := range fn.Instructions {
		cg.generateInstruction(&ins)
	}

	// Добавляем неявный return для void, если его нет
	if fn.ReturnType == "void" && len(fn.Instructions) > 0 {
		lastIns := fn.Instructions[len(fn.Instructions)-1]
		if lastIns.Op != "ret" {
			cg.writeLine("    return;")
		}
	}

	cg.writeLine("}")
	cg.writeLine("")
}

func (cg *CodeGenerator) generateInstruction(ins *IRInstruction) {
	indent := "    "

	switch ins.Op {
	case "label":
		cg.writeLine(fmt.Sprintf("%s:", ins.Result))

	case "inline_c":
		lines := strings.Split(ins.Arg1, "\n")
		for _, line := range lines {
			if strings.TrimSpace(line) != "" {
				cg.writeLine(fmt.Sprintf("%s%s", indent, line))
			}
		}

	case "strcat":
		// Конкатенация строк: выделяем память и копируем
		cg.writeLine(fmt.Sprintf("%schar %s[256];", indent, ins.Result))
		cg.writeLine(fmt.Sprintf("%sstrcpy(%s, %s);", indent, ins.Result, ins.Arg1))
		cg.writeLine(fmt.Sprintf("%sstrcat(%s, %s);", indent, ins.Result, ins.Arg2))

	case "to_string":
		// Преобразование числа в строку
		cg.writeLine(fmt.Sprintf("%schar %s[32];", indent, ins.Result))
		cg.writeLine(fmt.Sprintf("%ssnprintf(%s, 32, \"%%d\", %s);", indent, ins.Result, ins.Arg1))

	case "ret":
		if ins.Arg1 != "" {
			cg.writeLine(fmt.Sprintf("%sreturn %s;", indent, ins.Arg1))
		} else {
			cg.writeLine(fmt.Sprintf("%sreturn;", indent))
		}

	case "call":
		if ins.Result != "" {
			// Вызов с сохранением результата
			cg.writeLine(fmt.Sprintf("%s%s = %s(%s);", indent, ins.Result, ins.Arg1, ins.Arg2))
		} else {
			// Вызов без сохранения результата (void)
			cg.writeLine(fmt.Sprintf("%s%s(%s);", indent, ins.Arg1, ins.Arg2))
		}

	case "$":
		// Преобразование в строку
		cg.writeLine(fmt.Sprintf("%schar %s[32];", indent, ins.Result))
		cg.writeLine(fmt.Sprintf("%ssnprintf(%s, 32, \"%%d\", %s);", indent, ins.Result, ins.Arg1))

	case "if":
		cg.writeLine(fmt.Sprintf("%sif (%s) {", indent, ins.Result))
		cg.writeLine(fmt.Sprintf("%s    goto %s;", indent, ins.Arg1))
		cg.writeLine(fmt.Sprintf("%s} else {", indent))
		cg.writeLine(fmt.Sprintf("%s    goto %s;", indent, ins.Arg2))
		cg.writeLine(fmt.Sprintf("%s}", indent))

	case "goto":
		cg.writeLine(fmt.Sprintf("%sgoto %s;", indent, ins.Result))

	case "=":
		if strings.HasPrefix(ins.Result, "t") {
			argType := cg.inferType(ins.Arg1)
			cg.writeLine(fmt.Sprintf("%s%s %s = %s;", indent, argType, ins.Result, ins.Arg1))
		} else {
			cg.writeLine(fmt.Sprintf("%s%s = %s;", indent, ins.Result, ins.Arg1))
		}

	case "+", "-", "*", "/":
		if strings.HasPrefix(ins.Result, "t") {
			cg.writeLine(fmt.Sprintf("%sint %s = %s %s %s;", indent, ins.Result, ins.Arg1, ins.Op, ins.Arg2))
		} else {
			cg.writeLine(fmt.Sprintf("%s%s = %s %s %s;", indent, ins.Result, ins.Arg1, ins.Op, ins.Arg2))
		}

	default:
		if ins.Result != "" && ins.Arg1 != "" && ins.Arg2 != "" {
			cg.writeLine(fmt.Sprintf("%s%s %s %s %s;", indent, ins.Result, ins.Op, ins.Arg1, ins.Arg2))
		} else if ins.Result != "" && ins.Arg1 != "" {
			cg.writeLine(fmt.Sprintf("%s%s %s %s;", indent, ins.Result, ins.Op, ins.Arg1))
		} else {
			cg.writeLine(fmt.Sprintf("%s%s;", indent, ins.Result))
		}
	}
}

func (cg *CodeGenerator) typeToC(typ string) string {
	switch typ {
	case "int":
		return "int"
	case "string":
		return "sk_string"
	case "float":
		return "float"
	case "double":
		return "double"
	case "bool":
		return "sk_bool"
	case "char":
		return "char"
	case "void":
		return "void"
	case "arr":
		return "void*"
	case "dict":
		return "void*"
	case "any":
		return "void*"
	default:
		return "int"
	}
}

func (cg *CodeGenerator) inferType(value string) string {
	// Пытаемся определить тип по значению
	if strings.HasPrefix(value, `"`) && strings.HasSuffix(value, `"`) {
		return "sk_string"
	}

	// Проверяем, является ли число с плавающей точкой
	if strings.Contains(value, ".") {
		return "double"
	}

	// Проверяем, является ли целым числом
	if len(value) > 0 && (value[0] >= '0' && value[0] <= '9' || value[0] == '-') {
		return "int"
	}

	// По умолчанию
	return "int"
}

func (cg *CodeGenerator) writeLine(line string) {
	cg.CSource.WriteString(line + "\n")
}
